# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7728e6060207c8ba879cb0423c7cc3daa072e9a564e7be1b3a60ba8fba466f19776838250c1be4f35d09d5d29fc79ce4f7e78d10711106ad9ee8ccc0d667284

test:
  secret_key_base: 10c11515fbff30f8a81bb93291837e670bc7a292b34be5a276553c77fa2d667142df3d5f0b5fa739c79a9f8f7972219203363fa9ae9d9bd66677aec5ffe90c93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
